### PR TITLE
Deposit/Withdraw Integration

### LINKED ISSUE #1330: Integration of Direct Deposit & Withdrawal
## 📝 Description

We have already created packages for enabling direct deposits and withdrawal. Now, next task is to integrate them with UI so that direct deposits/withdrawal could be done from UI.

With Direct deposit, we can deposit tokens from any foreign chain to polkadex orderbook.
With Direct withdraw, we can withdraw tokens from polkadex orderbook to any foreign chain.

## Tasks - 

- [x] Depost Provider Integration
- [x] Withdraw Provider Integration
- [x] Validations for Deposits and withdrawals
- [x] Confirm transaction component
- [x] URL query to choose deposit/withdraw tab
- [x] Minor style fixes
- [x] Integrate History component
- [ ] Direct Withdraw when using extension proxy account

### PR DESCRIPTION
**Pull request by ap211unitech**
## 📝 Description

We have already created packages for enabling direct deposits and withdrawal. Now, next task is to integrate them with UI so that direct deposits/withdrawal could be done from UI.

With Direct deposit, we can deposit tokens from any foreign chain to polkadex orderbook.
With Direct withdraw, we can withdraw tokens from polkadex orderbook to any foreign chain.

## Tasks - 

- [x] Depost Provider Integration
- [x] Withdraw Provider Integration
- [x] Validations for Deposits and withdrawals
- [x] Confirm transaction component
- [x] URL query to choose deposit/withdraw tab
- [x] Minor style fixes
- [x] Integrate History component
- [ ] Direct Withdraw when using extension proxy account

## Note - 

CI is failing due to netlify issue. Build is successful.

image

## Checklist

- [x] Included link to corresponding [Polkadex Orderbook Frontend Issue](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/issues).
- [x] I have tested these changes thoroughly.
- [x] I have requested a review from at least one other contributor.

### CODE REVIEW

**Review by nuel77 — APPROVED** [review]

**Review by serhii-temchenko — APPROVED** [review]

**Review by minikas — COMMENTED** [review]
https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/12574469/d99e0d57-c4fa-47ec-9302-8af7ba7bba64

@nuel77 @ap211unitech I can't withdraw

**Review by minikas — COMMENTED** [review]
Screenshot 2024-06-26 at 05 46 37

@nuel77 Why do I have to perform an auto-swap when I have enough PDEX to cover the transaction fees?

**Review by minikas — COMMENTED** [review]
https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/12574469/01bac372-ae2c-4c0c-a8ea-fab0b2d92362

Similar issue with Phala. This time, validation is done before the confirmation popup. Perhaps we should standardize validations before or after confirmation? (Some validations could be moved to the button instead of the tooltip, similar to Polkapool) - @nuel77 @ap211unitech @serhii-temchenko

**Review by minikas — COMMENTED** [review]
https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/12574469/438becab-5274-4b9f-b858-0605533330b8

The tooltip is closed and opened by clicking the button. 

I will leave this issue as a comment, as it might be better to remove this tooltip and add somewhere in the confirmation component.

**Review by minikas — CHANGES_REQUESTED** [review]
https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/12574469/909d5556-c91f-42d0-9847-40694ba00662

The MAX button works differently in withdraw and deposit.

**Review by minikas — CHANGES_REQUESTED** [review]
https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/12574469/c0c458ba-fcf4-45ce-81d0-2e82e5dc3105

@ap211unitech Please reset the form when switching networks & assets

**Comment by ap211unitech** [comment]
> Screen.Recording.2024-06-26.at.05.58.05.mov 
> @nuel77 @ap211unitech I can't withdraw

@minikas You should have DOT in AssetHub network. It will withdraw to AssetHub chain.

**Comment by ap211unitech** [comment]
> Screen.Recording.2024-06-26.at.06.15.16.mov 
> The MAX button works differently in withdraw and deposit.

@minikas What is the issue here ? It's working as expected.

**Comment by ap211unitech** [comment]
> Screen.Recording.2024-06-26.at.06.23.46.mov 
> @ap211unitech Please reset the form when switching networks & assets

@minikas This is added now.

**Comment by minikas** [comment]
> > Screen.Recording.2024-06-26.at.05.58.05.mov
> > @nuel77 @ap211unitech I can't withdraw
> 
> @minikas You should have DOT in AssetHub network. It will withdraw to AssetHub chain.



> > Screen.Recording.2024-06-26.at.05.58.05.mov
> > @nuel77 @ap211unitech I can't withdraw
> 
> @minikas You should have DOT in AssetHub network. It will withdraw to AssetHub chain.

@ap211unitech  DOT to pay the fee or for existential purposes, or exactly why? 
@nuel77 Shouldn't we inform the user about this (maybe a component with this kind of information)?

**Comment by ap211unitech** [comment]
> > > Screen.Recording.2024-06-26.at.05.58.05.mov
> > > @nuel77 @ap211unitech I can't withdraw
> > 
> > 
> > @minikas You should have DOT in AssetHub network. It will withdraw to AssetHub chain.
> 
> > > Screen.Recording.2024-06-26.at.05.58.05.mov
> > > @nuel77 @ap211unitech I can't withdraw
> > 
> > 
> > @minikas You should have DOT in AssetHub network. It will withdraw to AssetHub chain.
> 
> @ap211unitech DOT to pay the fee or for existential purposes, or exactly why? @nuel77 Shouldn't we inform the user about this (maybe a component with this kind of information)?

@minikas Whenever we do a bridge transfer, Destionation account must have existential amount in destination chain else bridge ttransfer will fail.

**Review by minikas — APPROVED** [review]

**Pull request merged**
